# Generated by Django 4.2.17 on 2025-01-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsAPI', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='post',
        ),
    ]
