# Generated by Django 4.2.17 on 2025-01-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsAPI', '0006_rename_content_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(default='', max_length=500),
        ),
    ]
